# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab3_part1/lab1_constraints.xdc

# Block Designs: bd/lab2_block/lab2_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block || ORIG_REF_NAME==lab2_block}]

# IP: bd/lab2_block/ip/lab2_block_processing_system7_0_0/lab2_block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_processing_system7_0_0 || ORIG_REF_NAME==lab2_block_processing_system7_0_0}]

# IP: bd/lab2_block/ip/lab2_block_axi_gpio_0_0/lab2_block_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_axi_gpio_0_0 || ORIG_REF_NAME==lab2_block_axi_gpio_0_0}]

# IP: bd/lab2_block/ip/lab2_block_ps7_0_axi_periph_0/lab2_block_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab2_block_ps7_0_axi_periph_0}]

# IP: bd/lab2_block/ip/lab2_block_rst_ps7_0_100M_0/lab2_block_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab2_block_rst_ps7_0_100M_0}]

# IP: bd/lab2_block/ip/lab2_block_axi_gpio_0_1/lab2_block_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_axi_gpio_0_1 || ORIG_REF_NAME==lab2_block_axi_gpio_0_1}]

# IP: bd/lab2_block/ip/lab2_block_xbar_0/lab2_block_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_xbar_0 || ORIG_REF_NAME==lab2_block_xbar_0}]

# IP: bd/lab2_block/ip/lab2_block_led_ip_0_0/lab2_block_led_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_led_ip_0_0 || ORIG_REF_NAME==lab2_block_led_ip_0_0}]

# IP: bd/lab2_block/ip/lab2_block_auto_pc_0/lab2_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lab2_block_auto_pc_0 || ORIG_REF_NAME==lab2_block_auto_pc_0}]

# XDC: bd/lab2_block/lab2_block_ooc.xdc
