# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.cache/wt [current_project]
set_property parent.project_path /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/inf2015/dchristodoulou/CE435/LAB3/LAB3_PART1/ip_repo/led_ip_1.0 [current_project]
set_property ip_output_repo /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/imports/hdl/lab2_block_wrapper.v
add_files /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/lab2_block.bd
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_processing_system7_0_0/lab2_block_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_axi_gpio_0_0/lab2_block_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_axi_gpio_0_0/lab2_block_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_axi_gpio_0_0/lab2_block_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_rst_ps7_0_100M_0/lab2_block_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_rst_ps7_0_100M_0/lab2_block_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_rst_ps7_0_100M_0/lab2_block_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_axi_gpio_0_1/lab2_block_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_axi_gpio_0_1/lab2_block_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_axi_gpio_0_1/lab2_block_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_xbar_0/lab2_block_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/ip/lab2_block_auto_pc_0/lab2_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/lab2_block_ooc.xdc]
set_property is_locked true [get_files /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/sources_1/bd/lab2_block/lab2_block.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/constrs_1/imports/lab3_part1/lab1_constraints.xdc
set_property used_in_implementation false [get_files /home/inf2015/dchristodoulou/CE435/LAB3/Part3_new/project_3.srcs/constrs_1/imports/lab3_part1/lab1_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top lab2_block_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef lab2_block_wrapper.dcp

catch { report_utilization -file lab2_block_wrapper_utilization_synth.rpt -pb lab2_block_wrapper_utilization_synth.pb }
